const provinciasIds = [
    "Ciudad Autonoma de Buenos Aires",
    "Buenos Aires",
    "Catamarca",
    "Cordoba",
    "Corrientes",
    "Chaco",
    "Chubut",
    "Entre Rios",
    "Formosa",
    "Jujuy",
    "La Pampa",
    "La Rioja",
    "Mendoza",
    "Misiones",
    "Neuquen",
    "Salta",
    "San Juan",
    "San Luis",
    "Santa Cruz",
    "Santa Fe",
    "Santiago del Estero",
    "Tucuman"
  ];
  